### PR TITLE
[Phalanx] Add workaround to fix clock stretching issue

### PR DESCRIPTION
**Pull request by pphuchar**
## Phalanx switchboard driver chnages 
 * Add cpu_relax to cond_reched to reduce cpu load.
 * Initialize I2C core before perform every transaction.
 * Update i2c control state and polling for stop bit mechanism.
 * Add retry when error occur in smbus data receiving state.

## Fishbone32 switchboard driver changes 
TBD after phalanx

### CODE REVIEW

**Comment by larryming** [comment]
Could we use a common code for 3 projects?

**Comment by larryming** [comment]
For Arbitration lost, fishbone48 and Phalanx return different value:
-EAGAIN, -EBUSY

Why?

**Comment by larryming** [comment]
Why do you move the following code from phalanx_init to fpga_pci_probe? It  is different from fishbone48.
    platform_device_register(&phalanx_dev);
    platform_driver_register(&phalanx_drv);

**Comment by pphuchar** [comment]
> Why do you move the following code from phalanx_init to fpga_pci_probe? It is different from fishbone48.
> platform_device_register(&phalanx_dev);
> platform_driver_register(&phalanx_drv);

The change applies to all platforms in this commit.
https://github.com/celestica-Inc/sonic-platform-modules-cel/pull/38

**Comment by pphuchar** [comment]
> Could we use a common code for 3 projects?

Each project has different I2C topology mapping.
For the core function like i2c_access, i2c_wait_ack, i2c_stop we can make it common.

**Comment by pphuchar** [comment]
> For Arbitration lost, fishbone48 and Phalanx return different value:
> -EAGAIN, -EBUSY
> 
> Why?

The -EAGAIN was changed to -EBUSY after this changes applied on Fishbone48 too.
https://github.com/celestica-Inc/sonic-platform-modules-cel/commit/f3ddb0cda61bf133142fc60a1bfbcaa0ebc53501#diff-eade4c98a6c7b6615f97d439e458c365

The latest Fisbone48 codes is here:
https://github.com/celestica-Inc/sonic-platform-modules-cel/blob/ali-phalanx-fishbone-201811/fishbone48/modules/switchboard_fpga.c

**Comment by pphuchar** [comment]
This PR is deprecated, the fix was merged with another PR already.
I will close this one.

**Pull request closed without merging**
